[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "test-contract"

[proxy]
enabled = true
address = "0x96c4119dde2fda7ad5a2515542b1a9218260772ebf10c6c85f5eae210246c95a"

[dependencies]
